export const userData = {
    username: 'karenlq',
    password: '6522903Lq',
    url: 'https://www.demoblaze.com/index.html',
    browser: 'chrome',
    1: 'Samsung galaxy s6',
    2: 'Nokia lumia 1520',
    3: 'Nexus 6',
    4: 'Samsung galaxy s7',
    5: 'Iphone 6 32gb',
    6: 'Sony xperia z5',
    7: 'HTC One M9',
    8: 'Sony vaio i5',
    9: 'Sony vaio i7',
    10: 'Apple monitor 24',
    11: 'MacBook air',
    12: 'Dell i7 8gb',
    13: '2017 Dell 15.6 Inch',
    14: 'ASUS Full HD',
    15: 'MacBook Pro',
}